# This file intentionally left blank
BOOTMAGIC_ENABLE = yes

LTO_ENABLE = yes
KEY_LOCK_ENABLE = no

CONSOLE_ENABLE = no
COMMAND_ENABLE = no
MOUSEKEY_ENABLE = no
EXTRAKEY_ENABLE = no

SPACE_CADET_ENABLE = no
GRAVE_ESC_ENABLE = no 
MAGIC_ENABLE = no

MUSIC_ENABLE = no
AUDIO_ENABLE = no
RGBLIGHT_ENABLE = no
BACKLIGHT_ENABLE = no
MIDI_ENABLE = no

